### ISSUE TITLE
  wisol.SEND_RCV(Concatenation); 

### ISSUE THREAD

**Issue by anorna** [TECA-IOT/Tinyfox#12]
Habeis probado el comando  wisol.SEND_RCV(Concatenation); ?

              String rec= ( wisol.SEND_RCV(Concatenation)); //aproximandamente esperar 1 minuto   
              Serial.print("valor_recibido: ");
               Serial.println(rec);

Estoy probando a obtener el string de respuesta pero no recibo  nada y el programa se queda queda colgado indefinidamente

**Comment by paulporto** [comment]
en que arquitectura tienes ese problema? lo acabo de probar con leonardo y funciona correctemente? puedes pegar todo el codigo?

note un detalle en la libreria en la linea 114
dice: for(int a=0;a<=buffersize;a++){cadena_cad[a]= 0x00;}
pero deberia decir for(int a=0;a<buffersize;a++){cadena_cad[a]= 0x00;}
puede probar con ese cambio? me avisa si eso lo soluciona, gracias

**Comment by anorna** [comment]
si, he corregido ese detalle  en la linea 114 y en la linea 52 y ahora funciona correctamente:

 //Debug->println(cmd);
  long lastMsg = millis();
  caracter = 0x00;
  i = 0;
 for(int a=0;a<buffersize;a++){cadena_cad[a]= 0x00;} //  antes  de corregir a=0;a<=buffersize;a++){cadena_cad[a]= 0x00
  Modulo->println(cmd);
  do{


Muchas gracias
